baseurl = "/"
languageCode = "en-us"
title = "Mathieu Bray"
theme = "blackburn"
author = "Mathieu Bray"
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 10
enableEmoji = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "PhD Candidate. Biostatistics. Data Science"
  brand = "Mathieu Bray"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "mathieubray"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006"
  custom_css = ["css/mathieubray_css.css"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "CV"
    pre = "<i class='fa fa-file-pdf-o fa-fw'></i>"
    weight = 3
    url = "/cv.pdf"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "mathieubray"
  github = "mathieubray"
  linkedin = "mathieubray"
